name: Release CI No Cloud NGFW
run-name: "Continous Release No Cloud NGFW"

permissions:
  contents: write
  issues: read
  id-token: write

on:
  workflow_dispatch:
concurrency: release

jobs:
  release_wrkflw:
    name: Do release
    uses: PaloAltoNetworks/terraform-modules-swfw-ci-workflows/.github/workflows/release_ci.yml@exclude-cloudngfw-idempotence
    if: github.actor != 'dependabot[bot]'
    secrets: inherit
    with:
      cloud: aws
      validate_max_parallel: 20
      test_max_parallel: 5
      terratest_action: Idempotence # keep in mind that this has to start with capital letter
      fail_fast: false
      apply_timeout: 120
